# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Leeung/Projects/LUTsofLUV/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_17/base_m00_regslice_17.xci
# IP: The module: 'base_m00_regslice_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leeung/Projects/LUTsofLUV/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_17/base_m00_regslice_17_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_17'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Leeung/Projects/LUTsofLUV/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_17/base_m00_regslice_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Leeung/Projects/LUTsofLUV/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_17/base_m00_regslice_17.xci
# IP: The module: 'base_m00_regslice_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leeung/Projects/LUTsofLUV/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_17/base_m00_regslice_17_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Leeung/Projects/LUTsofLUV/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_17/base_m00_regslice_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
