// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="color_convert_color_convert,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.520000,HLS_SYN_LAT=7,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=916,HLS_SYN_LUT=1053,HLS_VERSION=2024_2}" *)

module color_convert (
        ap_clk,
        ap_rst_n,
        stream_in_24_TDATA,
        stream_in_24_TVALID,
        stream_in_24_TREADY,
        stream_in_24_TKEEP,
        stream_in_24_TSTRB,
        stream_in_24_TUSER,
        stream_in_24_TLAST,
        stream_out_24_TDATA,
        stream_out_24_TVALID,
        stream_out_24_TREADY,
        stream_out_24_TKEEP,
        stream_out_24_TSTRB,
        stream_out_24_TUSER,
        stream_out_24_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] stream_in_24_TDATA;
input   stream_in_24_TVALID;
output   stream_in_24_TREADY;
input  [2:0] stream_in_24_TKEEP;
input  [2:0] stream_in_24_TSTRB;
input  [0:0] stream_in_24_TUSER;
input  [0:0] stream_in_24_TLAST;
output  [23:0] stream_out_24_TDATA;
output   stream_out_24_TVALID;
input   stream_out_24_TREADY;
output  [2:0] stream_out_24_TKEEP;
output  [2:0] stream_out_24_TSTRB;
output  [0:0] stream_out_24_TUSER;
output  [0:0] stream_out_24_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire  signed [9:0] c1_c1;
wire   [9:0] c1_c2;
wire   [9:0] c1_c3;
wire  signed [9:0] c2_c1;
wire   [9:0] c2_c2;
wire   [9:0] c2_c3;
wire  signed [9:0] c3_c1;
wire   [9:0] c3_c2;
wire   [9:0] c3_c3;
wire   [9:0] bias_c1;
wire   [9:0] bias_c2;
wire   [9:0] bias_c3;
reg    stream_in_24_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
reg    stream_out_24_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter6;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter7;
reg   [2:0] curr_pixel_keep_reg_939;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_stream_out_24_V_data_V_U_apdone_blk;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] curr_pixel_keep_reg_939_pp0_iter1_reg;
reg   [2:0] curr_pixel_keep_reg_939_pp0_iter2_reg;
reg   [2:0] curr_pixel_keep_reg_939_pp0_iter3_reg;
reg   [2:0] curr_pixel_keep_reg_939_pp0_iter4_reg;
reg   [2:0] curr_pixel_keep_reg_939_pp0_iter5_reg;
reg   [2:0] curr_pixel_strb_reg_944;
reg   [2:0] curr_pixel_strb_reg_944_pp0_iter1_reg;
reg   [2:0] curr_pixel_strb_reg_944_pp0_iter2_reg;
reg   [2:0] curr_pixel_strb_reg_944_pp0_iter3_reg;
reg   [2:0] curr_pixel_strb_reg_944_pp0_iter4_reg;
reg   [2:0] curr_pixel_strb_reg_944_pp0_iter5_reg;
reg   [0:0] curr_pixel_user_reg_949;
reg   [0:0] curr_pixel_user_reg_949_pp0_iter1_reg;
reg   [0:0] curr_pixel_user_reg_949_pp0_iter2_reg;
reg   [0:0] curr_pixel_user_reg_949_pp0_iter3_reg;
reg   [0:0] curr_pixel_user_reg_949_pp0_iter4_reg;
reg   [0:0] curr_pixel_user_reg_949_pp0_iter5_reg;
reg   [0:0] curr_pixel_last_reg_954;
reg   [0:0] curr_pixel_last_reg_954_pp0_iter1_reg;
reg   [0:0] curr_pixel_last_reg_954_pp0_iter2_reg;
reg   [0:0] curr_pixel_last_reg_954_pp0_iter3_reg;
reg   [0:0] curr_pixel_last_reg_954_pp0_iter4_reg;
reg   [0:0] curr_pixel_last_reg_954_pp0_iter5_reg;
reg   [7:0] v_p2_reg_959;
reg   [7:0] v_p3_reg_964;
wire   [17:0] zext_ln32_fu_291_p1;
reg  signed [9:0] c1_c2_read_reg_981;
reg  signed [9:0] c1_c3_read_reg_986;
reg   [9:0] bias_c1_read_reg_991;
reg   [9:0] bias_c1_read_reg_991_pp0_iter1_reg;
reg   [9:0] bias_c1_read_reg_991_pp0_iter2_reg;
reg   [9:0] bias_c1_read_reg_991_pp0_iter3_reg;
reg  signed [9:0] c2_c2_read_reg_1001;
reg  signed [9:0] c2_c3_read_reg_1006;
reg   [9:0] bias_c2_read_reg_1011;
reg   [9:0] bias_c2_read_reg_1011_pp0_iter1_reg;
reg   [9:0] bias_c2_read_reg_1011_pp0_iter2_reg;
reg   [9:0] bias_c2_read_reg_1011_pp0_iter3_reg;
reg  signed [9:0] c3_c2_read_reg_1021;
reg  signed [9:0] c3_c3_read_reg_1026;
reg   [9:0] bias_c3_read_reg_1031;
reg   [9:0] bias_c3_read_reg_1031_pp0_iter1_reg;
reg   [9:0] bias_c3_read_reg_1031_pp0_iter2_reg;
reg   [9:0] bias_c3_read_reg_1031_pp0_iter3_reg;
wire   [17:0] mul_ln32_1_fu_313_p2;
reg  signed [17:0] mul_ln32_1_reg_1036;
wire   [17:0] zext_ln32_2_fu_319_p1;
wire   [17:0] mul_ln33_1_fu_328_p2;
reg  signed [17:0] mul_ln33_1_reg_1053;
wire   [17:0] mul_ln34_1_fu_340_p2;
reg  signed [17:0] mul_ln34_1_reg_1063;
reg   [0:0] tmp_reg_1103;
reg   [7:0] trunc_ln_reg_1109;
reg   [0:0] tmp_1_reg_1114;
reg   [0:0] tmp_2_reg_1119;
reg   [3:0] tmp_3_reg_1125;
reg   [0:0] tmp_5_reg_1131;
reg   [7:0] trunc_ln1_reg_1137;
reg   [0:0] tmp_6_reg_1142;
reg   [0:0] tmp_7_reg_1147;
reg   [3:0] tmp_8_reg_1153;
reg   [0:0] tmp_10_reg_1159;
reg   [7:0] trunc_ln2_reg_1165;
reg   [0:0] tmp_11_reg_1170;
reg   [0:0] tmp_13_reg_1175;
reg   [3:0] tmp_s_reg_1181;
wire   [7:0] out1_fu_646_p3;
reg   [7:0] out1_reg_1187;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [7:0] out2_fu_756_p3;
reg   [7:0] out2_reg_1192;
wire   [7:0] out3_fu_866_p3;
reg   [7:0] out3_reg_1197;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [7:0] v_p1_fu_271_p1;
wire   [7:0] mul_ln32_1_fu_313_p1;
wire   [17:0] zext_ln32_1_fu_307_p1;
wire   [7:0] mul_ln33_1_fu_328_p1;
wire   [7:0] mul_ln34_1_fu_340_p1;
wire  signed [18:0] grp_fu_882_p3;
wire  signed [18:0] grp_fu_891_p3;
wire  signed [18:0] grp_fu_900_p3;
wire   [17:0] shl_ln_fu_367_p3;
wire  signed [19:0] sext_ln32_7_fu_374_p1;
wire  signed [19:0] grp_fu_909_p3;
(* use_dsp48 = "no" *) wire   [19:0] add_ln32_2_fu_378_p2;
wire   [17:0] shl_ln1_fu_426_p3;
wire  signed [19:0] sext_ln33_7_fu_433_p1;
wire  signed [19:0] grp_fu_919_p3;
(* use_dsp48 = "no" *) wire   [19:0] add_ln33_2_fu_437_p2;
wire   [17:0] shl_ln2_fu_485_p3;
wire  signed [19:0] sext_ln34_7_fu_492_p1;
wire  signed [19:0] grp_fu_929_p3;
(* use_dsp48 = "no" *) wire   [19:0] add_ln34_2_fu_496_p2;
wire   [7:0] zext_ln32_3_fu_544_p1;
wire   [7:0] add_ln32_3_fu_547_p2;
wire   [0:0] icmp_ln32_1_fu_565_p2;
wire   [0:0] tmp_4_fu_557_p3;
wire   [0:0] icmp_ln32_fu_552_p2;
wire   [0:0] xor_ln32_fu_570_p2;
wire   [0:0] select_ln32_fu_576_p3;
wire   [0:0] or_ln32_fu_584_p2;
wire   [0:0] not_tmp_2_fu_597_p2;
wire   [0:0] empty_28_fu_602_p2;
wire   [0:0] empty_27_fu_590_p3;
wire   [0:0] or_ln32_1_fu_613_p2;
wire   [0:0] and_ln32_fu_608_p2;
wire   [0:0] xor_ln32_1_fu_618_p2;
wire   [7:0] select_ln32_1_fu_630_p3;
wire   [0:0] or_ln32_2_fu_624_p2;
wire   [7:0] select_ln32_2_fu_638_p3;
wire   [7:0] zext_ln33_fu_654_p1;
wire   [7:0] add_ln33_3_fu_657_p2;
wire   [0:0] icmp_ln33_1_fu_675_p2;
wire   [0:0] tmp_9_fu_667_p3;
wire   [0:0] icmp_ln33_fu_662_p2;
wire   [0:0] xor_ln33_fu_680_p2;
wire   [0:0] select_ln33_fu_686_p3;
wire   [0:0] or_ln33_fu_694_p2;
wire   [0:0] not_tmp_7_fu_707_p2;
wire   [0:0] empty_30_fu_712_p2;
wire   [0:0] empty_29_fu_700_p3;
wire   [0:0] or_ln33_1_fu_723_p2;
wire   [0:0] and_ln33_fu_718_p2;
wire   [0:0] xor_ln33_1_fu_728_p2;
wire   [7:0] select_ln33_1_fu_740_p3;
wire   [0:0] or_ln33_2_fu_734_p2;
wire   [7:0] select_ln33_2_fu_748_p3;
wire   [7:0] zext_ln34_fu_764_p1;
wire   [7:0] add_ln34_3_fu_767_p2;
wire   [0:0] icmp_ln34_1_fu_785_p2;
wire   [0:0] tmp_14_fu_777_p3;
wire   [0:0] icmp_ln34_fu_772_p2;
wire   [0:0] xor_ln34_fu_790_p2;
wire   [0:0] select_ln34_fu_796_p3;
wire   [0:0] or_ln34_fu_804_p2;
wire   [0:0] not_tmp_11_fu_817_p2;
wire   [0:0] empty_32_fu_822_p2;
wire   [0:0] empty_31_fu_810_p3;
wire   [0:0] or_ln34_1_fu_833_p2;
wire   [0:0] and_ln34_fu_828_p2;
wire   [0:0] xor_ln34_1_fu_838_p2;
wire   [7:0] select_ln34_1_fu_850_p3;
wire   [0:0] or_ln34_2_fu_844_p2;
wire   [7:0] select_ln34_2_fu_858_p3;
wire   [7:0] grp_fu_882_p1;
wire   [7:0] grp_fu_891_p1;
wire   [7:0] grp_fu_900_p1;
wire   [7:0] grp_fu_909_p1;
wire   [7:0] grp_fu_919_p1;
wire   [7:0] grp_fu_929_p1;
reg    grp_fu_882_ce;
reg    grp_fu_891_ce;
reg    grp_fu_900_ce;
reg    grp_fu_909_ce;
reg    grp_fu_919_ce;
reg    grp_fu_929_ce;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_stream_in_24_V_data_V_U_apdone_blk;
wire   [23:0] stream_in_24_TDATA_int_regslice;
wire    stream_in_24_TVALID_int_regslice;
reg    stream_in_24_TREADY_int_regslice;
wire    regslice_both_stream_in_24_V_data_V_U_ack_in;
wire    regslice_both_stream_in_24_V_keep_V_U_apdone_blk;
wire   [2:0] stream_in_24_TKEEP_int_regslice;
wire    regslice_both_stream_in_24_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_24_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_24_V_strb_V_U_apdone_blk;
wire   [2:0] stream_in_24_TSTRB_int_regslice;
wire    regslice_both_stream_in_24_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_24_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_24_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_24_TUSER_int_regslice;
wire    regslice_both_stream_in_24_V_user_V_U_vld_out;
wire    regslice_both_stream_in_24_V_user_V_U_ack_in;
wire    regslice_both_stream_in_24_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_24_TLAST_int_regslice;
wire    regslice_both_stream_in_24_V_last_V_U_vld_out;
wire    regslice_both_stream_in_24_V_last_V_U_ack_in;
wire   [23:0] stream_out_24_TDATA_int_regslice;
reg    stream_out_24_TVALID_int_regslice;
wire    stream_out_24_TREADY_int_regslice;
wire    regslice_both_stream_out_24_V_data_V_U_vld_out;
wire    regslice_both_stream_out_24_V_keep_V_U_apdone_blk;
wire    regslice_both_stream_out_24_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_keep_V_U_vld_out;
wire    regslice_both_stream_out_24_V_strb_V_U_apdone_blk;
wire    regslice_both_stream_out_24_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_strb_V_U_vld_out;
wire    regslice_both_stream_out_24_V_user_V_U_apdone_blk;
wire    regslice_both_stream_out_24_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_user_V_U_vld_out;
wire    regslice_both_stream_out_24_V_last_V_U_apdone_blk;
wire    regslice_both_stream_out_24_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

color_convert_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .c1_c1(c1_c1),
    .c1_c2(c1_c2),
    .c1_c3(c1_c3),
    .c2_c1(c2_c1),
    .c2_c2(c2_c2),
    .c2_c3(c2_c3),
    .c3_c1(c3_c1),
    .c3_c2(c3_c2),
    .c3_c3(c3_c3),
    .bias_c1(bias_c1),
    .bias_c2(bias_c2),
    .bias_c3(bias_c3)
);

color_convert_mul_10s_8ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
mul_10s_8ns_18_1_1_U1(
    .din0(c1_c2_read_reg_981),
    .din1(mul_ln32_1_fu_313_p1),
    .dout(mul_ln32_1_fu_313_p2)
);

color_convert_mul_10s_8ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
mul_10s_8ns_18_1_1_U2(
    .din0(c2_c2_read_reg_1001),
    .din1(mul_ln33_1_fu_328_p1),
    .dout(mul_ln33_1_fu_328_p2)
);

color_convert_mul_10s_8ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
mul_10s_8ns_18_1_1_U3(
    .din0(c3_c2_read_reg_1021),
    .din1(mul_ln34_1_fu_340_p1),
    .dout(mul_ln34_1_fu_340_p2)
);

color_convert_mac_muladd_10s_8ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_10s_8ns_18s_19_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(c1_c1),
    .din1(grp_fu_882_p1),
    .din2(mul_ln32_1_reg_1036),
    .ce(grp_fu_882_ce),
    .dout(grp_fu_882_p3)
);

color_convert_mac_muladd_10s_8ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_10s_8ns_18s_19_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(c2_c1),
    .din1(grp_fu_891_p1),
    .din2(mul_ln33_1_reg_1053),
    .ce(grp_fu_891_ce),
    .dout(grp_fu_891_p3)
);

color_convert_mac_muladd_10s_8ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_10s_8ns_18s_19_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(c3_c1),
    .din1(grp_fu_900_p1),
    .din2(mul_ln34_1_reg_1063),
    .ce(grp_fu_900_ce),
    .dout(grp_fu_900_p3)
);

color_convert_mac_muladd_10s_8ns_19s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
mac_muladd_10s_8ns_19s_20_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(c1_c3_read_reg_986),
    .din1(grp_fu_909_p1),
    .din2(grp_fu_882_p3),
    .ce(grp_fu_909_ce),
    .dout(grp_fu_909_p3)
);

color_convert_mac_muladd_10s_8ns_19s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
mac_muladd_10s_8ns_19s_20_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(c2_c3_read_reg_1006),
    .din1(grp_fu_919_p1),
    .din2(grp_fu_891_p3),
    .ce(grp_fu_919_ce),
    .dout(grp_fu_919_p3)
);

color_convert_mac_muladd_10s_8ns_19s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
mac_muladd_10s_8ns_19s_20_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(c3_c3_read_reg_1026),
    .din1(grp_fu_929_p1),
    .din2(grp_fu_900_p3),
    .ce(grp_fu_929_ce),
    .dout(grp_fu_929_p3)
);

color_convert_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_in_24_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TDATA),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_data_V_U_ack_in),
    .data_out(stream_in_24_TDATA_int_regslice),
    .vld_out(stream_in_24_TVALID_int_regslice),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_data_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_24_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TKEEP),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_keep_V_U_ack_in),
    .data_out(stream_in_24_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_keep_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_keep_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_24_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TSTRB),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_strb_V_U_ack_in),
    .data_out(stream_in_24_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_strb_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_strb_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_24_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TUSER),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_user_V_U_ack_in),
    .data_out(stream_in_24_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_user_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_user_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_24_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TLAST),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_last_V_U_ack_in),
    .data_out(stream_in_24_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_last_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_last_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_out_24_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_24_TDATA_int_regslice),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(stream_out_24_TREADY_int_regslice),
    .data_out(stream_out_24_TDATA),
    .vld_out(regslice_both_stream_out_24_V_data_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_data_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_out_24_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(curr_pixel_keep_reg_939_pp0_iter5_reg),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_keep_V_U_ack_in_dummy),
    .data_out(stream_out_24_TKEEP),
    .vld_out(regslice_both_stream_out_24_V_keep_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_keep_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_out_24_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(curr_pixel_strb_reg_944_pp0_iter5_reg),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_strb_V_U_ack_in_dummy),
    .data_out(stream_out_24_TSTRB),
    .vld_out(regslice_both_stream_out_24_V_strb_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_strb_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_24_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(curr_pixel_user_reg_949_pp0_iter5_reg),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_user_V_U_ack_in_dummy),
    .data_out(stream_out_24_TUSER),
    .vld_out(regslice_both_stream_out_24_V_user_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_user_V_U_apdone_blk)
);

color_convert_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_24_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(curr_pixel_last_reg_954_pp0_iter5_reg),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_last_V_U_ack_in_dummy),
    .data_out(stream_out_24_TLAST),
    .vld_out(regslice_both_stream_out_24_V_last_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_c1_read_reg_991 <= bias_c1;
        bias_c1_read_reg_991_pp0_iter1_reg <= bias_c1_read_reg_991;
        bias_c2_read_reg_1011 <= bias_c2;
        bias_c2_read_reg_1011_pp0_iter1_reg <= bias_c2_read_reg_1011;
        bias_c3_read_reg_1031 <= bias_c3;
        bias_c3_read_reg_1031_pp0_iter1_reg <= bias_c3_read_reg_1031;
        c1_c2_read_reg_981 <= c1_c2;
        c1_c3_read_reg_986 <= c1_c3;
        c2_c2_read_reg_1001 <= c2_c2;
        c2_c3_read_reg_1006 <= c2_c3;
        c3_c2_read_reg_1021 <= c3_c2;
        c3_c3_read_reg_1026 <= c3_c3;
        curr_pixel_keep_reg_939 <= stream_in_24_TKEEP_int_regslice;
        curr_pixel_keep_reg_939_pp0_iter1_reg <= curr_pixel_keep_reg_939;
        curr_pixel_last_reg_954 <= stream_in_24_TLAST_int_regslice;
        curr_pixel_last_reg_954_pp0_iter1_reg <= curr_pixel_last_reg_954;
        curr_pixel_strb_reg_944 <= stream_in_24_TSTRB_int_regslice;
        curr_pixel_strb_reg_944_pp0_iter1_reg <= curr_pixel_strb_reg_944;
        curr_pixel_user_reg_949 <= stream_in_24_TUSER_int_regslice;
        curr_pixel_user_reg_949_pp0_iter1_reg <= curr_pixel_user_reg_949;
        mul_ln32_1_reg_1036 <= mul_ln32_1_fu_313_p2;
        mul_ln33_1_reg_1053 <= mul_ln33_1_fu_328_p2;
        mul_ln34_1_reg_1063 <= mul_ln34_1_fu_340_p2;
        v_p2_reg_959 <= {{stream_in_24_TDATA_int_regslice[15:8]}};
        v_p3_reg_964 <= {{stream_in_24_TDATA_int_regslice[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        bias_c1_read_reg_991_pp0_iter2_reg <= bias_c1_read_reg_991_pp0_iter1_reg;
        bias_c1_read_reg_991_pp0_iter3_reg <= bias_c1_read_reg_991_pp0_iter2_reg;
        bias_c2_read_reg_1011_pp0_iter2_reg <= bias_c2_read_reg_1011_pp0_iter1_reg;
        bias_c2_read_reg_1011_pp0_iter3_reg <= bias_c2_read_reg_1011_pp0_iter2_reg;
        bias_c3_read_reg_1031_pp0_iter2_reg <= bias_c3_read_reg_1031_pp0_iter1_reg;
        bias_c3_read_reg_1031_pp0_iter3_reg <= bias_c3_read_reg_1031_pp0_iter2_reg;
        curr_pixel_keep_reg_939_pp0_iter2_reg <= curr_pixel_keep_reg_939_pp0_iter1_reg;
        curr_pixel_keep_reg_939_pp0_iter3_reg <= curr_pixel_keep_reg_939_pp0_iter2_reg;
        curr_pixel_keep_reg_939_pp0_iter4_reg <= curr_pixel_keep_reg_939_pp0_iter3_reg;
        curr_pixel_keep_reg_939_pp0_iter5_reg <= curr_pixel_keep_reg_939_pp0_iter4_reg;
        curr_pixel_last_reg_954_pp0_iter2_reg <= curr_pixel_last_reg_954_pp0_iter1_reg;
        curr_pixel_last_reg_954_pp0_iter3_reg <= curr_pixel_last_reg_954_pp0_iter2_reg;
        curr_pixel_last_reg_954_pp0_iter4_reg <= curr_pixel_last_reg_954_pp0_iter3_reg;
        curr_pixel_last_reg_954_pp0_iter5_reg <= curr_pixel_last_reg_954_pp0_iter4_reg;
        curr_pixel_strb_reg_944_pp0_iter2_reg <= curr_pixel_strb_reg_944_pp0_iter1_reg;
        curr_pixel_strb_reg_944_pp0_iter3_reg <= curr_pixel_strb_reg_944_pp0_iter2_reg;
        curr_pixel_strb_reg_944_pp0_iter4_reg <= curr_pixel_strb_reg_944_pp0_iter3_reg;
        curr_pixel_strb_reg_944_pp0_iter5_reg <= curr_pixel_strb_reg_944_pp0_iter4_reg;
        curr_pixel_user_reg_949_pp0_iter2_reg <= curr_pixel_user_reg_949_pp0_iter1_reg;
        curr_pixel_user_reg_949_pp0_iter3_reg <= curr_pixel_user_reg_949_pp0_iter2_reg;
        curr_pixel_user_reg_949_pp0_iter4_reg <= curr_pixel_user_reg_949_pp0_iter3_reg;
        curr_pixel_user_reg_949_pp0_iter5_reg <= curr_pixel_user_reg_949_pp0_iter4_reg;
        tmp_10_reg_1159 <= add_ln34_2_fu_496_p2[32'd19];
        tmp_11_reg_1170 <= grp_fu_929_p3[32'd7];
        tmp_13_reg_1175 <= add_ln34_2_fu_496_p2[32'd15];
        tmp_1_reg_1114 <= grp_fu_909_p3[32'd7];
        tmp_2_reg_1119 <= add_ln32_2_fu_378_p2[32'd15];
        tmp_3_reg_1125 <= {{add_ln32_2_fu_378_p2[19:16]}};
        tmp_5_reg_1131 <= add_ln33_2_fu_437_p2[32'd19];
        tmp_6_reg_1142 <= grp_fu_919_p3[32'd7];
        tmp_7_reg_1147 <= add_ln33_2_fu_437_p2[32'd15];
        tmp_8_reg_1153 <= {{add_ln33_2_fu_437_p2[19:16]}};
        tmp_reg_1103 <= add_ln32_2_fu_378_p2[32'd19];
        tmp_s_reg_1181 <= {{add_ln34_2_fu_496_p2[19:16]}};
        trunc_ln1_reg_1137 <= {{add_ln33_2_fu_437_p2[15:8]}};
        trunc_ln2_reg_1165 <= {{add_ln34_2_fu_496_p2[15:8]}};
        trunc_ln_reg_1109 <= {{add_ln32_2_fu_378_p2[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        out1_reg_1187 <= out1_fu_646_p3;
        out2_reg_1192 <= out2_fu_756_p3;
        out3_reg_1197 <= out3_fu_866_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_882_ce = 1'b1;
    end else begin
        grp_fu_882_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_891_ce = 1'b1;
    end else begin
        grp_fu_891_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_900_ce = 1'b1;
    end else begin
        grp_fu_900_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_909_ce = 1'b1;
    end else begin
        grp_fu_909_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_919_ce = 1'b1;
    end else begin
        grp_fu_919_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_929_ce = 1'b1;
    end else begin
        grp_fu_929_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_24_TDATA_blk_n = stream_in_24_TVALID_int_regslice;
    end else begin
        stream_in_24_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_24_TREADY_int_regslice = 1'b1;
    end else begin
        stream_in_24_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1)))) begin
        stream_out_24_TDATA_blk_n = stream_out_24_TREADY_int_regslice;
    end else begin
        stream_out_24_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        stream_out_24_TVALID_int_regslice = 1'b1;
    end else begin
        stream_out_24_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_2_fu_378_p2 = ($signed(sext_ln32_7_fu_374_p1) + $signed(grp_fu_909_p3));

assign add_ln32_3_fu_547_p2 = (trunc_ln_reg_1109 + zext_ln32_3_fu_544_p1);

assign add_ln33_2_fu_437_p2 = ($signed(sext_ln33_7_fu_433_p1) + $signed(grp_fu_919_p3));

assign add_ln33_3_fu_657_p2 = (trunc_ln1_reg_1137 + zext_ln33_fu_654_p1);

assign add_ln34_2_fu_496_p2 = ($signed(sext_ln34_7_fu_492_p1) + $signed(grp_fu_929_p3));

assign add_ln34_3_fu_767_p2 = (trunc_ln2_reg_1165 + zext_ln34_fu_764_p1);

assign and_ln32_fu_608_p2 = (tmp_reg_1103 & empty_28_fu_602_p2);

assign and_ln33_fu_718_p2 = (tmp_5_reg_1131 & empty_30_fu_712_p2);

assign and_ln34_fu_828_p2 = (tmp_10_reg_1159 & empty_32_fu_822_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)) | ((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & ((regslice_both_stream_out_24_V_data_V_U_apdone_blk == 1'b1) | ((stream_out_24_TREADY_int_regslice == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)))) | ((1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)) | ((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & ((regslice_both_stream_out_24_V_data_V_U_apdone_blk == 1'b1) | ((stream_out_24_TREADY_int_regslice == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)))) | ((1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = (((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)) | ((stream_out_24_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (stream_in_24_TVALID_int_regslice == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_27_fu_590_p3 = ((tmp_2_reg_1119[0:0] == 1'b1) ? select_ln32_fu_576_p3 : icmp_ln32_fu_552_p2);

assign empty_28_fu_602_p2 = (or_ln32_fu_584_p2 | not_tmp_2_fu_597_p2);

assign empty_29_fu_700_p3 = ((tmp_7_reg_1147[0:0] == 1'b1) ? select_ln33_fu_686_p3 : icmp_ln33_fu_662_p2);

assign empty_30_fu_712_p2 = (or_ln33_fu_694_p2 | not_tmp_7_fu_707_p2);

assign empty_31_fu_810_p3 = ((tmp_13_reg_1175[0:0] == 1'b1) ? select_ln34_fu_796_p3 : icmp_ln34_fu_772_p2);

assign empty_32_fu_822_p2 = (or_ln34_fu_804_p2 | not_tmp_11_fu_817_p2);

assign grp_fu_882_p1 = zext_ln32_fu_291_p1;

assign grp_fu_891_p1 = zext_ln32_fu_291_p1;

assign grp_fu_900_p1 = zext_ln32_fu_291_p1;

assign grp_fu_909_p1 = zext_ln32_2_fu_319_p1;

assign grp_fu_919_p1 = zext_ln32_2_fu_319_p1;

assign grp_fu_929_p1 = zext_ln32_2_fu_319_p1;

assign icmp_ln32_1_fu_565_p2 = ((tmp_3_reg_1125 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_552_p2 = ((tmp_3_reg_1125 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln33_1_fu_675_p2 = ((tmp_8_reg_1153 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_662_p2 = ((tmp_8_reg_1153 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_1_fu_785_p2 = ((tmp_s_reg_1181 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_772_p2 = ((tmp_s_reg_1181 == 4'd0) ? 1'b1 : 1'b0);

assign mul_ln32_1_fu_313_p1 = zext_ln32_1_fu_307_p1;

assign mul_ln33_1_fu_328_p1 = zext_ln32_1_fu_307_p1;

assign mul_ln34_1_fu_340_p1 = zext_ln32_1_fu_307_p1;

assign not_tmp_11_fu_817_p2 = (tmp_13_reg_1175 ^ 1'd1);

assign not_tmp_2_fu_597_p2 = (tmp_2_reg_1119 ^ 1'd1);

assign not_tmp_7_fu_707_p2 = (tmp_7_reg_1147 ^ 1'd1);

assign or_ln32_1_fu_613_p2 = (tmp_reg_1103 | empty_27_fu_590_p3);

assign or_ln32_2_fu_624_p2 = (xor_ln32_1_fu_618_p2 | and_ln32_fu_608_p2);

assign or_ln32_fu_584_p2 = (xor_ln32_fu_570_p2 | tmp_4_fu_557_p3);

assign or_ln33_1_fu_723_p2 = (tmp_5_reg_1131 | empty_29_fu_700_p3);

assign or_ln33_2_fu_734_p2 = (xor_ln33_1_fu_728_p2 | and_ln33_fu_718_p2);

assign or_ln33_fu_694_p2 = (xor_ln33_fu_680_p2 | tmp_9_fu_667_p3);

assign or_ln34_1_fu_833_p2 = (tmp_10_reg_1159 | empty_31_fu_810_p3);

assign or_ln34_2_fu_844_p2 = (xor_ln34_1_fu_838_p2 | and_ln34_fu_828_p2);

assign or_ln34_fu_804_p2 = (xor_ln34_fu_790_p2 | tmp_14_fu_777_p3);

assign out1_fu_646_p3 = ((or_ln32_2_fu_624_p2[0:0] == 1'b1) ? select_ln32_2_fu_638_p3 : add_ln32_3_fu_547_p2);

assign out2_fu_756_p3 = ((or_ln33_2_fu_734_p2[0:0] == 1'b1) ? select_ln33_2_fu_748_p3 : add_ln33_3_fu_657_p2);

assign out3_fu_866_p3 = ((or_ln34_2_fu_844_p2[0:0] == 1'b1) ? select_ln34_2_fu_858_p3 : add_ln34_3_fu_767_p2);

assign select_ln32_1_fu_630_p3 = ((and_ln32_fu_608_p2[0:0] == 1'b1) ? 8'd0 : add_ln32_3_fu_547_p2);

assign select_ln32_2_fu_638_p3 = ((or_ln32_1_fu_613_p2[0:0] == 1'b1) ? select_ln32_1_fu_630_p3 : 8'd255);

assign select_ln32_fu_576_p3 = ((tmp_4_fu_557_p3[0:0] == 1'b1) ? icmp_ln32_fu_552_p2 : icmp_ln32_1_fu_565_p2);

assign select_ln33_1_fu_740_p3 = ((and_ln33_fu_718_p2[0:0] == 1'b1) ? 8'd0 : add_ln33_3_fu_657_p2);

assign select_ln33_2_fu_748_p3 = ((or_ln33_1_fu_723_p2[0:0] == 1'b1) ? select_ln33_1_fu_740_p3 : 8'd255);

assign select_ln33_fu_686_p3 = ((tmp_9_fu_667_p3[0:0] == 1'b1) ? icmp_ln33_fu_662_p2 : icmp_ln33_1_fu_675_p2);

assign select_ln34_1_fu_850_p3 = ((and_ln34_fu_828_p2[0:0] == 1'b1) ? 8'd0 : add_ln34_3_fu_767_p2);

assign select_ln34_2_fu_858_p3 = ((or_ln34_1_fu_833_p2[0:0] == 1'b1) ? select_ln34_1_fu_850_p3 : 8'd255);

assign select_ln34_fu_796_p3 = ((tmp_14_fu_777_p3[0:0] == 1'b1) ? icmp_ln34_fu_772_p2 : icmp_ln34_1_fu_785_p2);

assign sext_ln32_7_fu_374_p1 = $signed(shl_ln_fu_367_p3);

assign sext_ln33_7_fu_433_p1 = $signed(shl_ln1_fu_426_p3);

assign sext_ln34_7_fu_492_p1 = $signed(shl_ln2_fu_485_p3);

assign shl_ln1_fu_426_p3 = {{bias_c2_read_reg_1011_pp0_iter3_reg}, {8'd0}};

assign shl_ln2_fu_485_p3 = {{bias_c3_read_reg_1031_pp0_iter3_reg}, {8'd0}};

assign shl_ln_fu_367_p3 = {{bias_c1_read_reg_991_pp0_iter3_reg}, {8'd0}};

assign stream_in_24_TREADY = regslice_both_stream_in_24_V_data_V_U_ack_in;

assign stream_out_24_TDATA_int_regslice = {{{out3_reg_1197}, {out2_reg_1192}}, {out1_reg_1187}};

assign stream_out_24_TVALID = regslice_both_stream_out_24_V_data_V_U_vld_out;

assign tmp_14_fu_777_p3 = add_ln34_3_fu_767_p2[32'd7];

assign tmp_4_fu_557_p3 = add_ln32_3_fu_547_p2[32'd7];

assign tmp_9_fu_667_p3 = add_ln33_3_fu_657_p2[32'd7];

assign v_p1_fu_271_p1 = stream_in_24_TDATA_int_regslice[7:0];

assign xor_ln32_1_fu_618_p2 = (or_ln32_1_fu_613_p2 ^ 1'd1);

assign xor_ln32_fu_570_p2 = (icmp_ln32_1_fu_565_p2 ^ 1'd1);

assign xor_ln33_1_fu_728_p2 = (or_ln33_1_fu_723_p2 ^ 1'd1);

assign xor_ln33_fu_680_p2 = (icmp_ln33_1_fu_675_p2 ^ 1'd1);

assign xor_ln34_1_fu_838_p2 = (or_ln34_1_fu_833_p2 ^ 1'd1);

assign xor_ln34_fu_790_p2 = (icmp_ln34_1_fu_785_p2 ^ 1'd1);

assign zext_ln32_1_fu_307_p1 = v_p2_reg_959;

assign zext_ln32_2_fu_319_p1 = v_p3_reg_964;

assign zext_ln32_3_fu_544_p1 = tmp_1_reg_1114;

assign zext_ln32_fu_291_p1 = v_p1_fu_271_p1;

assign zext_ln33_fu_654_p1 = tmp_6_reg_1142;

assign zext_ln34_fu_764_p1 = tmp_11_reg_1170;


reg find_kernel_block = 0;
// synthesis translate_off
`include "color_convert_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //color_convert

