# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/LUTsofLUV/maths-accelerator/overlay/base/base.runs/synth_1/base_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/LUTsofLUV/maths-accelerator/overlay/base/base.cache/wt [current_project]
set_property parent.project_path C:/LUTsofLUV/maths-accelerator/overlay/base/base.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/LUTsofLUV/maths-accelerator/overlay/ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/LUTsofLUV/maths-accelerator/overlay/base/base.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/hdl/base_wrapper.v
add_files C:/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/sources_1/bd/base/base.bd
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_xbar_0/base_axi_interconnect_0_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s00_regslice_2/base_axi_interconnect_0_imp_s00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s00_regslice_2/base_axi_interconnect_0_imp_s00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s01_regslice_0/base_axi_interconnect_0_imp_s01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s01_regslice_0/base_axi_interconnect_0_imp_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s02_regslice_0/base_axi_interconnect_0_imp_s02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s02_regslice_0/base_axi_interconnect_0_imp_s02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m00_regslice_2/base_axi_interconnect_0_imp_m00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m00_regslice_2/base_axi_interconnect_0_imp_m00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_pc_0/base_axi_interconnect_0_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_xbar_0/base_axi_mem_intercon_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s00_regslice_2/base_axi_mem_intercon_imp_s00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s00_regslice_2/base_axi_mem_intercon_imp_s00_regslice_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_us_0/base_axi_mem_intercon_imp_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_us_0/base_axi_mem_intercon_imp_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_us_0/base_axi_mem_intercon_imp_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s01_regslice_2/base_axi_mem_intercon_imp_s01_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s01_regslice_2/base_axi_mem_intercon_imp_s01_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_m00_regslice_2/base_axi_mem_intercon_imp_m00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_m00_regslice_2/base_axi_mem_intercon_imp_m00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_pc_0/base_axi_mem_intercon_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_protocol_convert_0_0/base_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_arduino_gpio_0/base_arduino_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_arduino_gpio_0/base_arduino_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_arduino_gpio_0/base_arduino_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ck_gpio_0/base_ck_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ck_gpio_0/base_ck_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ck_gpio_0/base_ck_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_iic_direct_0/base_iic_direct_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_iic_direct_0/base_iic_direct_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_0/base_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_0/base_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_0/base_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_0/base_intr_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_0/base_intr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_0/base_intr_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_dlmb_v10_0/base_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ilmb_v10_0/base_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_lmb_bram_0/base_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_lmb_bram_if_cntlr_0/base_lmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_0/base_mb_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_0/base_mb_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_0/base_mb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_bram_ctrl_0/base_mb_bram_ctrl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_xbar_0/base_microblaze_0_axi_periph_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_tier2_xbar_0_0/base_microblaze_0_axi_periph_imp_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_tier2_xbar_1_0/base_microblaze_0_axi_periph_imp_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_tier2_xbar_2_0/base_microblaze_0_axi_periph_imp_tier2_xbar_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_s00_regslice_3/base_microblaze_0_axi_periph_imp_s00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_s00_regslice_3/base_microblaze_0_axi_periph_imp_s00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m00_regslice_3/base_microblaze_0_axi_periph_imp_m00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m00_regslice_3/base_microblaze_0_axi_periph_imp_m00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m01_regslice_3/base_microblaze_0_axi_periph_imp_m01_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m01_regslice_3/base_microblaze_0_axi_periph_imp_m01_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m02_regslice_3/base_microblaze_0_axi_periph_imp_m02_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m02_regslice_3/base_microblaze_0_axi_periph_imp_m02_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m03_regslice_3/base_microblaze_0_axi_periph_imp_m03_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m03_regslice_3/base_microblaze_0_axi_periph_imp_m03_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m04_regslice_3/base_microblaze_0_axi_periph_imp_m04_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m04_regslice_3/base_microblaze_0_axi_periph_imp_m04_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m05_regslice_3/base_microblaze_0_axi_periph_imp_m05_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m05_regslice_3/base_microblaze_0_axi_periph_imp_m05_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m06_regslice_3/base_microblaze_0_axi_periph_imp_m06_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m06_regslice_3/base_microblaze_0_axi_periph_imp_m06_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m07_regslice_3/base_microblaze_0_axi_periph_imp_m07_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m07_regslice_3/base_microblaze_0_axi_periph_imp_m07_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m08_regslice_0/base_microblaze_0_axi_periph_imp_m08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m08_regslice_0/base_microblaze_0_axi_periph_imp_m08_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m09_regslice_0/base_microblaze_0_axi_periph_imp_m09_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m09_regslice_0/base_microblaze_0_axi_periph_imp_m09_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m10_regslice_0/base_microblaze_0_axi_periph_imp_m10_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m10_regslice_0/base_microblaze_0_axi_periph_imp_m10_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m11_regslice_0/base_microblaze_0_axi_periph_imp_m11_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m11_regslice_0/base_microblaze_0_axi_periph_imp_m11_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m12_regslice_0/base_microblaze_0_axi_periph_imp_m12_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m12_regslice_0/base_microblaze_0_axi_periph_imp_m12_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m13_regslice_0/base_microblaze_0_axi_periph_imp_m13_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m13_regslice_0/base_microblaze_0_axi_periph_imp_m13_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m14_regslice_0/base_microblaze_0_axi_periph_imp_m14_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m14_regslice_0/base_microblaze_0_axi_periph_imp_m14_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m15_regslice_0/base_microblaze_0_axi_periph_imp_m15_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m15_regslice_0/base_microblaze_0_axi_periph_imp_m15_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m16_regslice_0/base_microblaze_0_axi_periph_imp_m16_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m16_regslice_0/base_microblaze_0_axi_periph_imp_m16_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_0/base_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_0/base_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_0/base_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_direct_0/base_spi_direct_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_direct_0/base_spi_direct_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_direct_0/base_spi_direct_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_direct_0/base_spi_direct_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_shared_0/base_spi_shared_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_shared_0/base_spi_shared_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_shared_0/base_spi_shared_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_shared_0/base_spi_shared_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_0_0/base_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_0_0/base_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_2_0/base_timer_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_2_0/base_timer_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_3_0/base_timer_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_3_0/base_timer_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_4_0/base_timer_4_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_4_0/base_timer_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_5_0/base_timer_5_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_5_0/base_timer_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_uartlite_0/base_uartlite_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_uartlite_0/base_uartlite_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_uartlite_0/base_uartlite_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_xadc_0/base_xadc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_xadc_0/base_xadc_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_gpio_0/base_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_gpio_0/base_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_gpio_0/base_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_iic_0/base_iic_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_iic_0/base_iic_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_1/base_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_1/base_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_1/base_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_1/base_intr_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_1/base_intr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_1/base_intr_1.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_dlmb_v10_1/base_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ilmb_v10_1/base_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_lmb_bram_1/base_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_lmb_bram_if_cntlr_1/base_lmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_1/base_mb_1.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_1/base_mb_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_1/base_mb_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_bram_ctrl_1/base_mb_bram_ctrl_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_xbar_1/base_microblaze_0_axi_periph_imp_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_s00_regslice_4/base_microblaze_0_axi_periph_imp_s00_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_s00_regslice_4/base_microblaze_0_axi_periph_imp_s00_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m00_regslice_4/base_microblaze_0_axi_periph_imp_m00_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m00_regslice_4/base_microblaze_0_axi_periph_imp_m00_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m01_regslice_4/base_microblaze_0_axi_periph_imp_m01_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m01_regslice_4/base_microblaze_0_axi_periph_imp_m01_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m02_regslice_4/base_microblaze_0_axi_periph_imp_m02_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m02_regslice_4/base_microblaze_0_axi_periph_imp_m02_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m03_regslice_4/base_microblaze_0_axi_periph_imp_m03_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m03_regslice_4/base_microblaze_0_axi_periph_imp_m03_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m04_regslice_4/base_microblaze_0_axi_periph_imp_m04_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m04_regslice_4/base_microblaze_0_axi_periph_imp_m04_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m05_regslice_4/base_microblaze_0_axi_periph_imp_m05_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m05_regslice_4/base_microblaze_0_axi_periph_imp_m05_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m06_regslice_4/base_microblaze_0_axi_periph_imp_m06_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m06_regslice_4/base_microblaze_0_axi_periph_imp_m06_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m07_regslice_4/base_microblaze_0_axi_periph_imp_m07_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m07_regslice_4/base_microblaze_0_axi_periph_imp_m07_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_1/base_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_1/base_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_1/base_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_0/base_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_0/base_spi_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_0/base_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_0/base_spi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_6/base_timer_6.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_6/base_timer_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_gpio_1/base_gpio_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_gpio_1/base_gpio_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_gpio_1/base_gpio_1.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_iic_1/base_iic_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_iic_1/base_iic_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_2/base_intc_2.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_2/base_intc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intc_2/base_intc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_2/base_intr_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_2/base_intr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_intr_2/base_intr_2.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_dlmb_v10_2/base_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ilmb_v10_2/base_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_lmb_bram_2/base_lmb_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_lmb_bram_if_cntlr_2/base_lmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_2/base_mb_2.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_2/base_mb_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_2/base_mb_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_bram_ctrl_2/base_mb_bram_ctrl_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_xbar_2/base_microblaze_0_axi_periph_imp_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_s00_regslice_5/base_microblaze_0_axi_periph_imp_s00_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_s00_regslice_5/base_microblaze_0_axi_periph_imp_s00_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m00_regslice_5/base_microblaze_0_axi_periph_imp_m00_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m00_regslice_5/base_microblaze_0_axi_periph_imp_m00_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m01_regslice_5/base_microblaze_0_axi_periph_imp_m01_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m01_regslice_5/base_microblaze_0_axi_periph_imp_m01_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m02_regslice_5/base_microblaze_0_axi_periph_imp_m02_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m02_regslice_5/base_microblaze_0_axi_periph_imp_m02_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m03_regslice_5/base_microblaze_0_axi_periph_imp_m03_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m03_regslice_5/base_microblaze_0_axi_periph_imp_m03_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m04_regslice_5/base_microblaze_0_axi_periph_imp_m04_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m04_regslice_5/base_microblaze_0_axi_periph_imp_m04_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m05_regslice_5/base_microblaze_0_axi_periph_imp_m05_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m05_regslice_5/base_microblaze_0_axi_periph_imp_m05_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m06_regslice_5/base_microblaze_0_axi_periph_imp_m06_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m06_regslice_5/base_microblaze_0_axi_periph_imp_m06_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m07_regslice_5/base_microblaze_0_axi_periph_imp_m07_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_microblaze_0_axi_periph_imp_m07_regslice_5/base_microblaze_0_axi_periph_imp_m07_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_2/base_rst_clk_wiz_1_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_2/base_rst_clk_wiz_1_100M_2.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_2/base_rst_clk_wiz_1_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_1/base_spi_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_1/base_spi_1.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_1/base_spi_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_spi_1/base_spi_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_7/base_timer_7.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_timer_7/base_timer_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_leds_gpio_0/base_leds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_leds_gpio_0/base_leds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_leds_gpio_0/base_leds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mdm_1_0/base_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mdm_1_0/base_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_0/base_ps7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_xbar_0/base_ps7_0_axi_periph_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_s00_regslice_0/base_ps7_0_axi_periph_imp_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_s00_regslice_0/base_ps7_0_axi_periph_imp_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_7/base_ps7_0_axi_periph_imp_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m00_regslice_0/base_ps7_0_axi_periph_imp_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m00_regslice_0/base_ps7_0_axi_periph_imp_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_0/base_ps7_0_axi_periph_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m01_regslice_0/base_ps7_0_axi_periph_imp_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m01_regslice_0/base_ps7_0_axi_periph_imp_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m02_regslice_0/base_ps7_0_axi_periph_imp_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m02_regslice_0/base_ps7_0_axi_periph_imp_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m03_regslice_0/base_ps7_0_axi_periph_imp_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m03_regslice_0/base_ps7_0_axi_periph_imp_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m04_regslice_0/base_ps7_0_axi_periph_imp_m04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m04_regslice_0/base_ps7_0_axi_periph_imp_m04_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m05_regslice_0/base_ps7_0_axi_periph_imp_m05_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m05_regslice_0/base_ps7_0_axi_periph_imp_m05_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_1/base_ps7_0_axi_periph_imp_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m06_regslice_0/base_ps7_0_axi_periph_imp_m06_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m06_regslice_0/base_ps7_0_axi_periph_imp_m06_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_2/base_ps7_0_axi_periph_imp_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m07_regslice_0/base_ps7_0_axi_periph_imp_m07_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m07_regslice_0/base_ps7_0_axi_periph_imp_m07_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_3/base_ps7_0_axi_periph_imp_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m08_regslice_0/base_ps7_0_axi_periph_imp_m08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m08_regslice_0/base_ps7_0_axi_periph_imp_m08_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_4/base_ps7_0_axi_periph_imp_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m09_regslice_0/base_ps7_0_axi_periph_imp_m09_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m09_regslice_0/base_ps7_0_axi_periph_imp_m09_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_5/base_ps7_0_axi_periph_imp_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m10_regslice_0/base_ps7_0_axi_periph_imp_m10_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_m10_regslice_0/base_ps7_0_axi_periph_imp_m10_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_imp_auto_pc_6/base_ps7_0_axi_periph_imp_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_xbar_0/base_ps7_0_axi_periph_1_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_s00_regslice_0/base_ps7_0_axi_periph_1_imp_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_s00_regslice_0/base_ps7_0_axi_periph_1_imp_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_auto_pc_0/base_ps7_0_axi_periph_1_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m00_regslice_0/base_ps7_0_axi_periph_1_imp_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m00_regslice_0/base_ps7_0_axi_periph_1_imp_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m01_regslice_0/base_ps7_0_axi_periph_1_imp_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m01_regslice_0/base_ps7_0_axi_periph_1_imp_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m02_regslice_0/base_ps7_0_axi_periph_1_imp_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m02_regslice_0/base_ps7_0_axi_periph_1_imp_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m03_regslice_0/base_ps7_0_axi_periph_1_imp_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph_1_imp_m03_regslice_0/base_ps7_0_axi_periph_1_imp_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk3_0/base_rst_ps7_0_fclk3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk3_0/base_rst_ps7_0_fclk3_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk3_0/base_rst_ps7_0_fclk3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_switches_gpio_0/base_switches_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_switches_gpio_0/base_switches_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_switches_gpio_0/base_switches_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_system_interrupts_0/base_system_interrupts_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_system_interrupts_0/base_system_interrupts_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_system_interrupts_0/base_system_interrupts_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axis_data_fifo_0_0/base_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_trace_cntrl_64_0_0/constraints/trace_cntrl_64_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_dma_0_1/base_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_dma_0_1/base_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_dma_0_1/base_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axis_data_fifo_0_1/base_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_trace_cntrl_32_0_0/constraints/trace_cntrl_32_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_xbar_1/base_axi_interconnect_0_imp_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s00_regslice_3/base_axi_interconnect_0_imp_s00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_s00_regslice_3/base_axi_interconnect_0_imp_s00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_pc_1/base_axi_interconnect_0_imp_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m00_regslice_3/base_axi_interconnect_0_imp_m00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m00_regslice_3/base_axi_interconnect_0_imp_m00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m01_regslice_0/base_axi_interconnect_0_imp_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m01_regslice_0/base_axi_interconnect_0_imp_m01_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_0/base_axi_interconnect_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_0/base_axi_interconnect_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_0/base_axi_interconnect_0_imp_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m02_regslice_0/base_axi_interconnect_0_imp_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m02_regslice_0/base_axi_interconnect_0_imp_m02_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_1/base_axi_interconnect_0_imp_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_1/base_axi_interconnect_0_imp_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_1/base_axi_interconnect_0_imp_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m03_regslice_0/base_axi_interconnect_0_imp_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m03_regslice_0/base_axi_interconnect_0_imp_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m04_regslice_0/base_axi_interconnect_0_imp_m04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m04_regslice_0/base_axi_interconnect_0_imp_m04_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m05_regslice_0/base_axi_interconnect_0_imp_m05_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m05_regslice_0/base_axi_interconnect_0_imp_m05_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m06_regslice_0/base_axi_interconnect_0_imp_m06_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m06_regslice_0/base_axi_interconnect_0_imp_m06_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_2/base_axi_interconnect_0_imp_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_2/base_axi_interconnect_0_imp_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_2/base_axi_interconnect_0_imp_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m07_regslice_0/base_axi_interconnect_0_imp_m07_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m07_regslice_0/base_axi_interconnect_0_imp_m07_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m08_regslice_0/base_axi_interconnect_0_imp_m08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m08_regslice_0/base_axi_interconnect_0_imp_m08_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m09_regslice_0/base_axi_interconnect_0_imp_m09_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_m09_regslice_0/base_axi_interconnect_0_imp_m09_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_xbar_1/base_axi_mem_intercon_imp_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s00_regslice_3/base_axi_mem_intercon_imp_s00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s00_regslice_3/base_axi_mem_intercon_imp_s00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s01_regslice_3/base_axi_mem_intercon_imp_s01_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_s01_regslice_3/base_axi_mem_intercon_imp_s01_regslice_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_us_1/base_axi_mem_intercon_imp_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_us_1/base_axi_mem_intercon_imp_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_us_1/base_axi_mem_intercon_imp_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_m00_regslice_3/base_axi_mem_intercon_imp_m00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_m00_regslice_3/base_axi_mem_intercon_imp_m00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_mem_intercon_imp_auto_pc_1/base_axi_mem_intercon_imp_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_vdma_0/base_axi_vdma_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_vdma_0/base_axi_vdma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_vdma_0/base_axi_vdma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_0/base_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_0/base_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_color_convert_0/constraints/color_convert_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_vtc_in_0/base_vtc_in_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_vtc_in_0/base_vtc_in_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_pixel_pack_0/constraints/pixel_pack_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_1/base_axis_register_slice_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_1/base_axis_register_slice_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_color_convert_1/constraints/color_convert_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_hdmi_out_hpd_video_0/base_hdmi_out_hpd_video_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_hdmi_out_hpd_video_0/base_hdmi_out_hpd_video_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_hdmi_out_hpd_video_0/base_hdmi_out_hpd_video_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_vtc_out_0/base_vtc_out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/constraints/pixel_unpack_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_proc_sys_reset_pixelclk_0/base_proc_sys_reset_pixelclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_proc_sys_reset_pixelclk_0/base_proc_sys_reset_pixelclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_proc_sys_reset_pixelclk_0/base_proc_sys_reset_pixelclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/base_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_1/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_mb_2/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/constrs_1/imports/src/base.xdc
set_property used_in_implementation false [get_files C:/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/constrs_1/imports/src/base.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/utils_1/imports/src/base_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top base_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef base_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file base_wrapper_utilization_synth.rpt -pb base_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
