# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3.xci
# IP: The module: 'base_axi_interconnect_0_imp_auto_cc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_interconnect_0_imp_auto_cc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_interconnect_0_imp_auto_cc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/LUTsofLUV/maths-accelerator/overlay/base/base.srcs/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3.xci
# IP: The module: 'base_axi_interconnect_0_imp_auto_cc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_interconnect_0_imp_auto_cc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/LUTsofLUV/maths-accelerator/overlay/base/base.gen/sources_1/bd/base/ip/base_axi_interconnect_0_imp_auto_cc_3/base_axi_interconnect_0_imp_auto_cc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_interconnect_0_imp_auto_cc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
